let content = [
  {
    profilpic: "assests/img/catwomen.jpg",
    name: "Catwoman",
    location: "Mauzhausen",
    image: "assests/img/katzen.jpg",
    likes: 345,
    mylike: [0],
    user:["katzenonkel43", "mauzi052"],
    comments: ["super süß", "*.*"],

  },
  {
    profilpic: "assests/img/catwomen.jpg",
    name: "Catwoman",
    location: "Mauzhausen",
    image: "assests/img/katzen.jpg",
    likes: 345,
    mylike: [0],
    comments: [],
  },
  {
    profilpic: "Profilbild",
    name: "Überschrift 1",
    location: "Ort 1",
    image: "img 1",
    comments: [],
  },
  {
    profilpic: "Profilbild",
    name: "Überschrift 1",
    location: "Ort 1",
    image: "img 1",
    comments: [],
  },
  {
    profilpic: "Profilbild",
    name: "Überschrift 1",
    location: "Ort 1",
    image: "img 1",
    comments: [],
  },
  {
    profilpic: "Profilbild",
    name: "Überschrift 1",
    location: "Ort 1",
    image: "img 1",
    comments: [],
  },
  {
    profilpic: "Profilbild",
    name: "Überschrift 1",
    location: "Ort 1",
    image: "img 1",
    comments: [],
  },
];
