let content = [
  {
    profilpic: "./assets/img/kochwelt.png",
    name: "Kochwelt161",
    location: "Deutschland",
    date: "24.04.2024",
    image: "./assets/img/mediterranean-chicken.jpg",
    likes: 345 ,
    mylike: false,
    description:"NEU!! Check unser Gericht des Tages!!",
    linksurl: ["#", "#"],
    link:["kochwelt","develperakademie"],
    user: ["feinschmecker62", "lafer36"],
    comments: ["Super lecker", "Ein Gedicht für den Gaumen"],
  },
  {
    profilpic: "./assets/img/catwomen.jpg",
    name: "Catwoman",
    location: "Maunzhausen",
    date: "03.12.2023",
    image: "./assets/img/katzen.jpg",
    likes: 1293,
    mylike: false,
    description:"Meine neuen Mitbewohner *-*",
    linksurl: [],
    link:[],
    user: ["Katzenonkel64", "mauzi052"],
    comments: ["Klasse", ":-*"],
  },
  {
    profilpic: "./assets/img/travelguide.jpg",
    name: "Travel Guide",
    location: "weltweit",
    date: "02.08.2021",
    image: "./assets/img/landscape.jpg",
    likes: 32,
    mylike: false,
    description:"Erlebe die pure Natur",
    linksurl: ["#","#","#"],
    link:["travelguide", "newisland","abindenurlaub"],
    user: ["reiselust20", "urlaubsreif", "naturbursche44"],
    comments: ["WOW", "Ich muss da hin","himmlisch"],
  },

];
